version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: blocksbom-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: blocksbom
      MYSQL_DATABASE: blocksbom
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - blocksbom-network

networks:
  blocksbom-network:
    driver: bridge

volumes:
  mysql_data: 